# Chart Releaser Configuration
# See: https://github.com/helm/chart-releaser/blob/main/README.md#configuration

# GitHub repository settings
owner: kenchrcum
repo: ansible-playbook-operator

# Chart directory
path: helm

# GitHub Pages settings
pages-branch: gh-pages
pages-index-path: index.yaml

# Release settings
charts-repo-url: https://github.com/kenchrcum/ansible-playbook-operator/releases/download
release-name-template: "{{ .Name }}-{{ .Version }}"

# Options
prerelease: false
debug: true
