operator:
  image:
    repository: kenchrcum/ansible-playbook-operator
    tag: "0.1.0"
    # Optional: pin image by digest for enhanced security and reproducibility
    # When digest is provided, it takes precedence over tag
    # Format: sha256:abc123def456...
    digest: ""
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  leaderElection: true
  watch:
    # one of: namespace|all
    scope: namespace
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
  serviceAccount:
    create: true
    name: ""

executorDefaults:
  image:
    repository: kenchrcum/ansible-runner
    tag: latest
    # Optional: pin image by digest for enhanced security and reproducibility
    # When digest is provided, it takes precedence over tag
    # Format: sha256:abc123def456...
    digest: ""
    pullPolicy: IfNotPresent
  cache:
    # Default cache strategy for repositories that don't specify one
    # Options: none, pvc
    strategy: none
    # Default PVC name when strategy is pvc
    pvcName: ""
    # Whether to create a PVC for caching (optional)
    createPVC: false
    # Storage size for the cache PVC when createPVC is true
    storageSize: "10Gi"
    # Storage class name for the cache PVC (optional)
    storageClassName: ""

rbac:
  # RBAC permission preset: minimal (default), scoped, or cluster-admin
  # minimal: least-privilege namespaced permissions for single-namespace operation
  # scoped: cross-namespace access for cluster-wide scenarios
  # cluster-admin: full cluster permissions (use with caution)
  preset: minimal

  # Enable cluster read permissions for Kopf preflight checks (CRDs, namespaces)
  # Only applies when preset is 'minimal'; ignored for other presets
  clusterRead: true

# CRDs will be delivered under crds/ in the chart (added later)
