operator:
  image:
    repository: kenchrcum/ansible-playbook-operator
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  leaderElection: true
  watch:
    # one of: namespace|all
    scope: namespace
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
  serviceAccount:
    create: true
    name: ""

executorDefaults:
  image:
    repository: kenchrcum/ansible-runner
    tag: latest
    pullPolicy: IfNotPresent

rbac:
  # RBAC permission preset: minimal (default), scoped, or cluster-admin
  # minimal: least-privilege namespaced permissions for single-namespace operation
  # scoped: cross-namespace access for multi-namespace scenarios
  # cluster-admin: full cluster permissions (use with caution)
  preset: minimal

  # Enable cluster read permissions for Kopf preflight checks (CRDs, namespaces)
  # Only applies when preset is 'minimal'; ignored for other presets
  clusterRead: true

# CRDs will be delivered under crds/ in the chart (added later)
