apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schedules.ansible.cloud37.dev
spec:
  group: ansible.cloud37.dev
  names:
    kind: Schedule
    listKind: ScheduleList
    plural: schedules
    singular: schedule
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Playbook
          jsonPath: .spec.playbookRef.name
          type: string
        - name: Schedule
          jsonPath: .status.computedSchedule
          type: string
        - name: Suspended
          jsonPath: .spec.suspend
          type: string
        - name: Ready
          jsonPath: .status.conditions[?(@.type=="Ready")].status
          type: string
        - name: Age
          jsonPath: .metadata.creationTimestamp
          type: date
      schema:
        openAPIV3Schema:
          type: object
          description: Scheduled execution of a Playbook via CronJob/Job
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required: [playbookRef, schedule]
              x-kubernetes-validations:
                - rule: "has(self.schedule) && size(self.schedule) > 0"
                  message: schedule must be a non-empty string
              properties:
                playbookRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                schedule:
                  type: string
                  description: Cron expression or one of @hourly-random, @daily-random, @weekly-random, @monthly-random, @yearly-random
                suspend:
                  type: boolean
                  default: false
                startingDeadlineSeconds:
                  type: integer
                concurrencyPolicy:
                  type: string
                  enum: [Allow, Forbid, Replace]
                  default: Forbid
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                    requests:
                      type: object
                backoffLimit:
                  type: integer
                  default: 3
                successfulJobsHistoryLimit:
                  type: integer
                  default: 1
                failedJobsHistoryLimit:
                  type: integer
                  default: 1
                ttlSecondsAfterFinished:
                  type: integer
                  default: 3600
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                  format: int64
                computedSchedule:
                  type: string
                lastRunTime:
                  type: string
                  format: date-time
                nextRunTime:
                  type: string
                  format: date-time
                lastJobRef:
                  type: string
                lastRunRevision:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    required: [type, status]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
