# Example Playbook CRD with custom executor image using digest pinning
# This demonstrates how to use digest-pinned images for specific playbooks

apiVersion: ansible.cloud37.dev/v1alpha1
kind: Playbook
metadata:
  name: example-playbook
  namespace: default
spec:
  # Repository reference
  repositoryRef:
    name: example-repo
    namespace: default

  # Playbook configuration
  playbookPath: "playbooks/main.yml"
  inventoryPath: "inventory/production"

  # Custom executor image with digest pinning
  runtime:
    image: "kenchrcum/ansible-runner@sha256:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Execution options
  execution:
    tags: ["deploy", "configure"]
    skipTags: ["test"]
    checkMode: false
    diff: true
    verbosity: 2
    limit: "production"
    connectionTimeout: 30
    forks: 5
    strategy: "free"
    flushCache: false
    forceHandlers: true

  # Extra variables
  extraVars:
    environment: "production"
    version: "1.0.0"
    debug: false

  # Secrets configuration
  secrets:
    env:
      - envVarName: "API_KEY"
        secretRef:
          name: "api-secrets"
          key: "key"
    envFromSecretRefs:
      - name: "app-secrets"
    vaultPasswordSecretRef:
      name: "vault-password"
    fileMounts:
      - key: "config"
        path: "/etc/app/config.yml"
        secretRef:
          name: "app-config"
          key: "config"

---
# Example Repository CRD
apiVersion: ansible.cloud37.dev/v1alpha1
kind: Repository
metadata:
  name: example-repo
  namespace: default
spec:
  url: "https://github.com/example/ansible-playbooks.git"
  branch: "main"
  revision: "abc123def456"

  # Authentication
  auth:
    method: "token"
    secretRef:
      name: "github-token"

  # SSH configuration
  ssh:
    strictHostKeyChecking: true
    knownHostsConfigMapRef:
      name: "github-known-hosts"

  # Cache configuration
  cache:
    strategy: "pvc"
    pvcName: "ansible-cache"

  # Git options
  git:
    submodules: true
    lfs: false
    shallow: false

---
# Example Schedule CRD
apiVersion: ansible.cloud37.dev/v1alpha1
kind: Schedule
metadata:
  name: example-schedule
  namespace: default
spec:
  # Playbook reference
  playbookRef:
    name: example-playbook
    namespace: default

  # Schedule configuration
  schedule: "0 2 * * *"  # Daily at 2 AM
  concurrencyPolicy: "Forbid"
  backoffLimit: 3
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  ttlSecondsAfterFinished: 3600
  startingDeadlineSeconds: 300

  # Resources override
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
