apiVersion: ansible.cloud37.dev/v1alpha1
kind: Playbook
metadata:
  name: web-deployment
  namespace: default
spec:
  repositoryRef:
    name: web-app-repo
  playbookPath: deploy/web.yml
  inventoryPath: inventory/production
  ansibleCfgPath: ansible/production.cfg
  extraVars:
    app_version: "1.2.3"
    environment: "production"
    debug_enabled: false
  execution:
    # Tag-based execution
    tags:
      - deploy
      - web
      - production
    skipTags:
      - test
      - debug
    # Execution mode
    checkMode: false
    diff: true
    verbosity: 2
    # Host targeting
    limit: "web_servers:&production"
    # Performance tuning
    connectionTimeout: 30
    forks: 10
    strategy: "free"
    # Advanced options
    flushCache: false
    forceHandlers: true
    step: false
    startAtTask: "Install packages"
  secrets:
    vaultPasswordSecretRef:
      name: ansible-vault-password
    env:
      - envVarName: "AWS_ACCESS_KEY_ID"
        secretRef:
          name: aws-credentials
          key: access-key
      - envVarName: "AWS_SECRET_ACCESS_KEY"
        secretRef:
          name: aws-credentials
          key: secret-key
    envFromSecretRefs:
      - name: database-credentials
  runtime:
    image: "kenchrcum/ansible-runner:latest"
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    activeDeadlineSeconds: 1800  # 30 minutes
---
apiVersion: ansible.cloud37.dev/v1alpha1
kind: Repository
metadata:
  name: web-app-repo
  namespace: default
spec:
  url: "https://github.com/company/web-app.git"
  branch: "main"
  auth:
    method: "token"
    secretRef:
      name: github-token
  cache:
    strategy: "pvc"
    pvcName: "ansible-cache-pvc"
---
apiVersion: ansible.cloud37.dev/v1alpha1
kind: Schedule
metadata:
  name: web-deployment-schedule
  namespace: default
spec:
  playbookRef:
    name: web-deployment
  schedule: "@daily-random"
  concurrencyPolicy: "Forbid"
  backoffLimit: 3
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  ttlSecondsAfterFinished: 3600
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
