apiVersion: ansible.cloud37.dev/v1alpha1
kind: Playbook
metadata:
  name: hello-world-config
spec:
  repositoryRef:
    name: sample-ssh
  playbookPath: playbooks/hello-world.yml
  inventoryPath: inventory/hosts
  secrets:
    fileMounts:
      - secretRef:
          name: ssh-credentials
        mountPath: /ssh-keys
        items:
          - key: ssh-privatekey
            path: id_rsa
  runtime:
    image: kenchrcum/ansible-runner:12
