---
# Repository with PVC-backed cache for Ansible collections and roles
# This improves performance for repositories that use many Galaxy collections
apiVersion: ansible.cloud37.dev/v1alpha1
kind: Repository
metadata:
  name: cached-ansible-repo
spec:
  url: https://github.com/myorg/ansible-automation.git
  branch: main
  auth:
    method: token
    secretRef:
      name: github-token
  # Enable PVC-backed caching for ~/.ansible collections/roles
  cache:
    strategy: pvc
    pvcName: ansible-cache-storage
  paths:
    playbookDir: playbooks
    inventoryDir: inventory
    requirementsFile: requirements.yml
