# Example Helm values demonstrating mixed image pinning configuration
# This file shows how to mix digest-pinned and tag-based images

# Operator image with digest pinning
operator:
  image:
    repository: kenchrcum/ansible-playbook-operator
    tag: "0.1.1"  # This tag is ignored when digest is present
    digest: "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  leaderElection: true
  watch:
    scope: namespace
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
  serviceAccount:
    create: true
    name: ""

# Executor image with tag-based fallback (no digest)
executorDefaults:
  image:
    repository: kenchrcum/ansible-runner
    tag: 13
    digest: ""  # Empty digest falls back to tag
    pullPolicy: IfNotPresent
  cache:
    strategy: none
    pvcName: ""
    createPVC: false
    storageSize: "10Gi"
    storageClassName: ""

# RBAC configuration
rbac:
  preset: minimal
  clusterRead: true

# Usage:
# helm install ansible-operator ./helm/ansible-playbook-operator \
#   --values examples/values-mixed-pinning.yaml \
#   --namespace ansible-operator-system
