{{- if and .Values.networkPolicies.enabled (ne .Values.networkPolicies.preset "none") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ansible-playbook-operator.fullname" . }}-executor
  labels:
    app.kubernetes.io/name: ansible-playbook-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: networkpolicy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ansible-playbook-operator-executor
  policyTypes:
    - Egress
  egress:
    {{- if eq .Values.networkPolicies.preset "restrictive" }}
    # Restrictive preset: Only Git endpoints and container registries
    {{- range .Values.networkPolicies.git.endpoints }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.git.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- range .Values.networkPolicies.git.custom }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.git.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- range .Values.networkPolicies.registries.endpoints }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.registries.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- range .Values.networkPolicies.registries.custom }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.registries.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- else if eq .Values.networkPolicies.preset "moderate" }}
    # Moderate preset: DNS, Git endpoints, registries, and Kubernetes API
    {{- if .Values.networkPolicies.dns.enabled }}
    # DNS resolution
    {{- range .Values.networkPolicies.dns.endpoints }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.dns.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- end }}
    # Git endpoints
    {{- range .Values.networkPolicies.git.endpoints }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.git.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- range .Values.networkPolicies.git.custom }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.git.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    # Container registries
    {{- range .Values.networkPolicies.registries.endpoints }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.registries.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- range .Values.networkPolicies.registries.custom }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.registries.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- if .Values.networkPolicies.kubernetes.enabled }}
    # Kubernetes API server
    {{- range .Values.networkPolicies.kubernetes.endpoints }}
    - to: []
      ports:
        {{- range $.Values.networkPolicies.kubernetes.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- end }}
    {{- else if eq .Values.networkPolicies.preset "permissive" }}
    # Permissive preset: Allow all egress (not recommended for production)
    - {}
    {{- end }}
    {{- if .Values.networkPolicies.additionalRules }}
    # Additional custom rules
    {{- toYaml .Values.networkPolicies.additionalRules | nindent 4 }}
    {{- end }}
{{- end }}
