{{- if .Values.executorDefaults.cache.createPVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-cache" (include "ansible-playbook-operator.fullname" .)) .Values.executorDefaults.cache.pvcName }}
  labels:
    app.kubernetes.io/name: ansible-playbook-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.executorDefaults.cache.storageSize | default "10Gi" }}
  {{- if .Values.executorDefaults.cache.storageClassName }}
  storageClassName: {{ .Values.executorDefaults.cache.storageClassName }}
  {{- end }}
{{- end }}
