apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ansible-playbook-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: ansible-playbook-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["events", "pods", "pods/log", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["ansible.cloud37.dev"]
    resources: ["repositories", "playbooks", "schedules"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["ansible.cloud37.dev"]
    resources: ["repositories/status", "playbooks/status", "schedules/status"]
    verbs: ["get", "update", "patch"]
